### PR TITLE
printer_tree: avoid NULL pointer dereference in trp_ext_is_present()

### PR DESCRIPTION
**Pull request by hugeping**

### CODE REVIEW

**Comment by lePici** [comment]
Thanks for the correction. Please change the base branch from `master` to `devel`, as the `devel` branch is intended for changes from PR.

**Comment by lePici** [comment]
Can you please give an example (YANG models, yanglint command...) when this error occurs? We need to see why the pointer is NULL.

**Comment by hugeping** [comment]
> Can you please give an example (YANG models, yanglint command...) when this error occurs? We need to see why the pointer is NULL.

shell.yang
<pre>
module shell {
  namespace "http://test.org/yang/shell";
  prefix "shell";
  extension password {
    argument "algo";
  }
}
</pre>
test-login.yang
<pre>
module test-login {
  namespace "http://test.ru/login";
  prefix "login";

  import "shell" { prefix "shell"; }
  import "test-system" { prefix "system"; }

  augment "/system:system" {
    container login {
      leaf passwd-hash {
        type string;
        shell:password plain;
      }
    }
  }
}
</pre>
test-system.yang
<pre>
module test-system {
  namespace "http://test.ru/system";
  prefix "system";
  contact "yang@test.ru";
  container system {
  }
}
</pre>

yanglint -f tree *.yang

**Comment by lePici** [comment]
Thank you for your cooperation.

**Pull request merged**
