### PR TITLE
c++ compatibility of public headers

### PR DESCRIPTION
**Pull request by rkrejci**
Rewrite macros to not use implicit casts - mentioned in #1504.

@choppsv1 - could you please check, that the changes help? I don't want to add `-Wc++-compat` directly to our build since the issues reported are fine from the C point of view and this is C code. I agree that the public headers are promising usability even for C++, so I tried to solve the issues there. Unfortunately, I'm not sure if there is a way to simply check only the (macros in) public headers.

### CODE REVIEW

**Comment by choppsv1** [comment]
> Unfortunately, I'm not sure if there is a way to simply check only the (macros in) public headers.

How about compile unit tests with -Werror=c++-compat?

**Review by michalvasko — APPROVED** [review]

**Comment by rkrejci** [comment]
> > Unfortunately, I'm not sure if there is a way to simply check only the (macros in) public headers.
> 
> How about compile unit tests with -Werror=c++-compat?

Then it covers the tests' code, so again false positives regarding the implicit cast of `void *` or conversion of `0` to enum values.

**Comment by choppsv1** [comment]
> > > Unfortunately, I'm not sure if there is a way to simply check only the (macros in) public headers.
> > 
> > 
> > How about compile unit tests with -Werror=c++-compat?
> 
> Then it covers the tests' code, so again false positives regarding the implicit cast of `void *` or conversion of `0` to enum values in *.c.

I ran into the issue b/c FRR has a c++-compat unit test, so perhaps a dedicated unit test that includes the public API headers and uses the macros? Not perfect but perhaps better than nothing.

**Comment by michalvasko** [comment]
Okay, such a "test" was added.

**Pull request merged**
