### PR TITLE
swig javascript BUGFIX add requirement cmake version 3.1+

### PR DESCRIPTION
**Pull request by mislavn**
Signed-off-by: Mislav Novakovic <mislav.novakovic@sartura.hr>

### CODE REVIEW

**Comment by rkrejci** [comment]
please update also requirement section in the js README, the main libyang README declares that cmake 2.6 is enough

**Comment by mislavn** [comment]
Yes I know, I will try to fix this if it is possible for now I am trying to find minimum requirements for building JavaScript bindings with the current setup.
At the moment I am testing minimum versions for swig, node and npm.

**Comment by rkrejci** [comment]
ok, I understand. Just for now, please make a note in [README](../blob/master/swig/javascript/README.md) and declare cmake version you are aware that is working. Then I will merge it and later you can update the requirements.

**Comment by mislavn** [comment]
I did add "cmake >= 3.1" inside the README file in a later forced push.

**Comment by rkrejci** [comment]
ah, I missed it, sorry

**Pull request merged**
