### PR TITLE
Internal unit tests devel

### PR DESCRIPTION
**Pull request by antonio-paunovic**
Hi Radek,
there are two tests added. Testing lyd_list_equal() is tested for simple cases which don't seem to change.
If the function is considered finished overall more complex cases (unique comparison) can be tested. 

Regards,
Antonio

### CODE REVIEW

**Comment by rkrejci** [comment]
There was a bug in `lyd_list_equal()` (see f045d1c), because lists without keys (which is possible in status data) should be considered as different - RFC 7950, sec. 4.2.2.4:
```
A list defines a sequence of list entries.  Each entry is like a
container and is uniquely identified by the values of its key leafs
if it has any key leafs defined.
```
Therefore the test now fails at `test_lyd_list_equal.c:121` because it expects that list instances without keys are supposed to be marked as duplication.

**Comment by mislavn** [comment]
Hi Radek,

we updated the license with a new git commit.

Regards,
Mislav

**Comment by rkrejci** [comment]
ok, but the `test_lyd_list_equal_no_action` is still wrong.

**Comment by mislavn** [comment]
Hi, I will fix it now.

**Comment by mislavn** [comment]
Hi Radek, the test now passed.

**Pull request merged**
