### PR TITLE
bindings CHANGE remove python CFFI bindings

### PR DESCRIPTION
**Pull request by rjarry**
For clarity, the CFFI bindings are now hosted in a separate repository: https://github.com/CESNET/libyang-python

### CODE REVIEW

**Comment by michalvasko** [comment]
Hi Robin,
never mind the failed NetDEF CI report, does not seem to be connected to your changes. But please keep the mention of these bindings in the README, with a link to your project.

Regards,
Michal

**Comment by michalvasko** [comment]
@rjarry Okay, it should be fine now and we will merge it once the CI problems are sorted out, thanks.

**Comment by rjarry** [comment]
Ok thanks Michal.

**Comment by mwinter-osr** [comment]
CI:rerun

**Pull request merged**
