### PR TITLE
tests/fuzz: New AFL target: function lyd_parse_path()

### PR DESCRIPTION
**Pull request by ikrumlova**
For each of the three supported formats: JSON, XML, LYB.
The JSON version crashes very quickly, xml after some time too.

### CODE REVIEW

**Comment by jvijtiuk** [comment]
Hello ikrumlova,

as the fuzzer harnesses are identical except for the lys_parse_path argument, maybe the wrappers could be unified into a single fuzz target that receives a command line argument which determines which file format to parse, so if you want you can unify the wrappers and update this PR.

It would be great if you could report the bugs that have been found, so that libyang2 can be checked for the same issues. 

Also, in #774 it was mentioned that only libyang2 should be fuzzed, from then on, so if that is still the case and you are fuzzing libyang I guess it would be best if you could fuzz only on the ```libyang2``` branch.

@rkrejci, @michalvasko, do you have any comments on this?

Regards,
Juraj

**Comment by rkrejci** [comment]
So far, I didn't have time to check the pull request, sorry.

However I'm fine even with fuzzing current master/devel. In this case, it is about fuzzing data formats parsers and it make sense. What I wanted to avoid is fuzzing YANG parser in master - we have very limited resources to fix it, so the schema formats should be really fuzzed in libyang2 branch.

**Comment by michalvasko** [comment]
Hi @ikrumlova,
actually, previously we were fixing problems uncovered by fuzzing in separate issues. It would be great if you could create issue with the input file that caused the crash, it significantly simplifies fixing it.

Regards,
Michal

**Comment by pspacek** [comment]
Sorry, this slipped through cracks, we will have a look.

**Comment by jvijtiuk** [comment]
Hello @pspacek, @ikrumlova,

have there been any updates regarding the JSON and XML crashes that were found?

Regards,
Juraj

**Comment by pspacek** [comment]
Sorry, there is no progress, we have to focus on other priorities. I would be more than happy if anyone else can take this forward.

**Comment by michalvasko** [comment]
Not needed for *libyang* 1 anymore.

**Pull request closed without merging**
