### PR TITLE
lyd_parse_mem parse rpc's output json will return NULL

### PR DESCRIPTION
**Pull request by yanjunxi**
[issue.txt](https://github.com/CESNET/libyang/files/497088/issue.txt)

### CODE REVIEW

**Comment by yanjunxi** [comment]
solve lyd_parse_mem can't parse rpc's output data by json format.

**Comment by michalvasko** [comment]
Hi,
the condition was added there on purpose because JSON parser is not currently able to parse RPC reply the way it should (XML parser is). Do you really need to parse RPC replies in JSON? If so, then I will make it fully working, I just thought it is not needed for now.

Regards,
Michal

**Comment by rkrejci** [comment]
This is supposed to have very low priority since JSON-encoded RPCs do not have real-world use case, do they?

**Comment by yanjunxi** [comment]
We do need transmit data between different module using json.
And I find it works well after deleting the code as I did in my case.

Thanks.

**Comment by rkrejci** [comment]
If you just need to transmit data, you do not need RPCs, do you? You can just dump the data tree.

**Comment by yanjunxi** [comment]
We need receive RPC command from one module(A), transmit the RPC's input information to another module(B), then receive the RPC's output info from module(B) and reply to module(A).
Between our module and module B must use json format data because of some other reasons.

Thanks.

**Pull request closed without merging**
