### PR TITLE
libyang internal test

### PR DESCRIPTION
**Pull request by antonio-paunovic**
Signed-off-by: Antonio Paunovic <antonio.paunovic@sartura.hr>
Signed-off-by: Mislav Novakovic <mislav.novakovic@sartura.hr>

### CODE REVIEW

**Comment by rkrejci** [comment]
I'm fine with the approach, but there are some things to fix:
- there is wrong path to the test binary in case of running it under valgrind (tests_internal/CMakeLists.txt:22 - there should be `/tests_internal/` instead of `/tests/`
- compiler has some warnings:
```
[ 77%] Building C object tests_internal/CMakeFiles/test_lys_find_grouping_up.dir/tree_internal/test_lys_find_grouping_up.c.o
/home/krejci/workspace/libyang/tests_internal/tree_internal/test_lys_find_grouping_up.c: In function ‘test_lys_find_grouping_up’:
/home/krejci/workspace/libyang/tests_internal/tree_internal/test_lys_find_grouping_up.c:107:21: warning: assignment from incompatible pointer type [enabled by default]
     node_no->parent = parent;
                     ^
/home/krejci/workspace/libyang/tests_internal/tree_internal/test_lys_find_grouping_up.c:61:34: warning: unused parameter ‘state’ [-Wunused-parameter]
 test_lys_find_grouping_up(void **state)
```
- the code is fine, but especially for the internal tests we will need much more comments inside, don't hesitate to use even ASCII art to show what is being created, what the test is going to check, what is the expected result, ...

**Comment by mislavn** [comment]
We made the changes as discussed, please can you take a look at it?

**Comment by rkrejci** [comment]
I don't see the change in the `sartura:internal_unit_tests_v2` branch. Please follow [this tutorial](https://help.github.com/articles/about-pull-requests/)

**Comment by antonio-paunovic** [comment]
There are few minor changes: warnings have been dealt with, cmake file fixed, and we added comments describing test cases and expectations. There were no other changes for this pull. Is this ok and did you have anything else in mind?

**Comment by rkrejci** [comment]
I prefer to have this work in devel branch for now. So instead of merging, I have cherry-picked your change (791c44d3) into devel branch and I'm going to close the pull request.

Next time please do changes to the original pull request as a separate commits (follow [this tutorial](https://help.github.com/articles/about-pull-requests/) to allow us to see and check what exactly has changed from the previous state.

Here are some notes about my changes added:
- comment the specific parts inside the function instead of making a big comment about a whole test function. In some cases the function may be quite long and it is better to have the description of the specific parts/cases together with the code.
- keep `{` `}` even for one-line if/for/while/... blocks

**Pull request closed without merging**
