### PR TITLE
Unit tests

### PR DESCRIPTION
**Pull request by mislavn**
Skeleton for unit testing the C++ and Python2/3 bindings.

### CODE REVIEW

**Comment by mislavn** [comment]
@michalvasko Python requires SWIG version >= 3.0.5, so I add a new commit which requires that.

Because of that travis fails. Please can you update travis.

**Comment by michalvasko** [comment]
Hi,
I can only include the RPM package with libyang, just like in sysrepo :)

Michal

**Comment by mislavn** [comment]
Hi,

in sysrepo they have a travis deploy script where swig 3.0.8 is installed: https://github.com/sysrepo/sysrepo/blob/master/deploy/travis/install-libs.sh#L11

Can you do something similar.

Mislav

**Comment by mislavn** [comment]
I'll try to fix the issue in the swigfile, give me a few hours.

Also what OS do you use for linux?

**Comment by michalvasko** [comment]
Hi Mislav,
I have included the package with libyang, just like in sysrepo, so no changes are probably required. I just wanted to wait for the travis build, to make sure it is installed properly.

Regards,
Michal

**Comment by michalvasko** [comment]
You can try to merge devel into your branch, it seems to have run with the old travis file.

**Comment by mislavn** [comment]
Thanks.

**Comment by mislavn** [comment]
Hi Michal,

is it possible to add >= swig 3.0.5 to OSX build?

Mislav

**Comment by michalvasko** [comment]
Okay, I will change it. Other than that, is this pull request ready?

**Comment by mislavn** [comment]
yes.

**Comment by michalvasko** [comment]
Fine, thanks.

**Comment by michalvasko** [comment]
Just a note, I could not get swig3 on mac so I turned language bindings off, otherwise it was not possible to build.

Regards,
Michal

**Comment by mislavn** [comment]
ok, thanks Michal

**Pull request merged**
