### PR TITLE
Get rid of volatile in favor of _Atomic

### PR DESCRIPTION
**Pull request by syyyr**
Hi, these things sometimes caused errors in our CI with ThreadSanitizer.

### CODE REVIEW

**Review by jktjkt — APPROVED** [review]

**Review by michalvasko — CHANGES_REQUESTED** [review]
Using `_Atomic` directly may cause compatibility problems (even if using `-std=c11`) so please use macros from `compat.h` instead. Also, you should then use compat macros for any access of these variables, relaxed (no) memory barrier should be fine.

**Comment by syyyr** [comment]
>Using _Atomic directly may cause compatibility problems (even if using -std=c11) so please use macros from compat.h instead. Also, you should then use compat macros for any access of these variables, relaxed (no) memory barrier should be fine.

Done, hopefully I got it right.

**Review by michalvasko — CHANGES_REQUESTED** [review]
Alright, seems fine to me except missing include for `compat.h` in `common.h`.

**Comment by syyyr** [comment]
I added the include

**Review by michalvasko — APPROVED** [review]

**Comment by michalvasko** [comment]
Fine, I have no more problems with it, merging.

**Pull request merged**
